### ISSUE TITLE
support for windows?

### ISSUE THREAD

**Issue by bwgjoseph** [hariprasanths/synchly#4]
Does this tool support windows machine too?

This is the log message I gotten after installing, does the error matter or can be safety ignore?

```
❯ npm i -g synchly
C:\Users\Joseph\AppData\Roaming\npm\synchly -> C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\bin\synchly

> node-cron@2.0.3 postinstall C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\node_modules\node-cron
> opencollective-postinstall

Thank you for using node-cron!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/node-cron/donate


> nodemailer@6.4.11 postinstall C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\node_modules\nodemailer
> node -e "try{require('./postinstall')}catch(e){}"

                           === Nodemailer 6.4.11 ===

Thank you for using Nodemailer for your email sending needs! While Nodemailer
itself is mostly meant to be a SMTP client there are other related projects in
the Nodemailer project as well.

> IMAP API (  https://imapapi.com  ) is a server application to easily access
  IMAP accounts via REST API
> ImapFlow (  https://imapflow.com/  ) is an async IMAP client library for
  Node.js
> NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform GUI app to
  debug emails
> Project Pending (  https://projectpending.com/  ) allows you to host DNS of
  your project domains
> Pending DNS (  https://pendingdns.com/  ) is the DNS server used that powers
  Project Pending
  accepts all your test emails

                            Don't like this message?
                  There's a Github Sponsors goal to remove it
                       https://github.com/sponsors/andris9

........

> synchly@0.1.0 postinstall C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly
> node scripts/postinstall.js

Error: Shell could not be detected
    at Omelette.getActiveShell (C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\node_modules\omelette\src\omelette.js:189:17)
    at Omelette.getDefaultShellInitFile (C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\node_modules\omelette\src\omelette.js:210:35)
    at Omelette.setupShellInitFile (C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\node_modules\omelette\src\omelette.js:238:42)
    at Object.<anonymous> (C:\Users\Joseph\AppData\Roaming\npm\node_modules\synchly\scripts\postinstall.js:6:16)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
+ synchly@0.1.0
added 187 packages from 136 contributors in 17.423s
```

And if so, where would the config be stored in?

**Comment by hariprasanths** [comment]
Nope, currently synchly doesn't support windows, most of the modules are linux specific for now.

**Comment by bwgjoseph** [comment]
Noted, and thank you. Is there any plan for windows support though?

**Comment by hariprasanths** [comment]
Yeah, it's definitely on the roadmap but its a bit far down the line.

**Comment by bwgjoseph** [comment]
Noted. Thank you.

Do you still want to keep this open? If not, you can close this.

**Comment by hariprasanths** [comment]
Let this issue be open so that it'll be easy to track the progress.

**Comment by hariprasanths** [comment]
#11 Synchly supports windows now. (Tab auto completion won't work though, which was the error you got in the post installation)

**Comment by bwgjoseph** [comment]
Thanks! Will give it a go in couple of days to test it out..
